apiVersion: v1
kind: Service
metadata:
  name: frontend-service-stable
  namespace: unibooker
spec:
  selector:
    app: frontend
    version: stable
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
